export const productConstants = {
    
    PRODUCT_ADD: 'PRODUCT_ADD',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_LIST: 'PRODUCT_LIST',
    PRODUCT_DELETE: 'PRODUCT_DELETE',
    PRODUCT_GET_BY_ID: 'PRODUCT_GET_BY_ID',
}